# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a5b93ed39255cb23a0bacbea8f23e074fd88b61beaece33d74c8c05a4cb85c575c43af46274210026fab284d0feeca800defda05a7bd0ca6f3d2909a938d4bc6

test:
  secret_key_base: bebece0d2064fa127c9197ae11c845e7b5746c5fcd6dd6e3edf48f2d28066b851b1bbbc004a28255d776dfd02a4049cd2e870540a9cb4ebcffc5fe9728199b1d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
